# Application Configuration - Production Environment
# ServiceNow <-> Salesforce ITSM Integration API

api:
  name: "salesforce-servicenow-api"
  version: "v1"
  basePath: "/api/v1"
  id: "${api.autodiscovery.id}"

http:
  listener:
    host: "0.0.0.0"
    port: "8081"
    basePath: "/api/v1"
  request:
    connectionTimeout: "30000"
    responseTimeout: "60000"
    connectionIdleTimeout: "30000"

salesforce:
  api:
    host: "prod-salesforce.my.salesforce.com"
    basePath: "/services/data/v58.0"
    port: "443"
    protocol: "HTTPS"
  oauth:
    tokenUrl: "/services/oauth2/token"

servicenow:
  api:
    host: "prod-instance.service-now.com"
    basePath: "/api/now/table"
    port: "443"
    protocol: "HTTPS"

retry:
  maxAttempts: "5"
  frequency: "3000"

objectstore:
  entryTtl: "2"
  entryTtlUnit: "HOURS"
  maxEntries: "5000"
  expirationInterval: "60"

logging:
  level: "INFO"
  maskFields: "password,secret,token,authorization"
